# Generated by Django 4.2.7 on 2023-11-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='programming_language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
