# Generated by Django 4.2.7 on 2023-11-15 19:05

from django.db import migrations
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blogpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='title')), ('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('quote', wagtail.blocks.BlockQuoteBlock(required=False)), ('video', wagtail.embeds.blocks.EmbedBlock(required=False))], use_json_field=True),
        ),
    ]
