# Generated by Django 4.2.7 on 2023-11-16 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_cloudinary_image', '0001_initial'),
        ('blog', '0010_alter_blogpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpagegalleryimage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtail_cloudinary_image.cloudinaryimage'),
        ),
    ]
