# Generated by Django 4.2.7 on 2023-11-20 18:08

import blog.custom
from django.db import migrations, models
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_blogpagegalleryimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='title')), ('paragraph', wagtail.blocks.RichTextBlock()), ('image', blog.custom.ImageChooserBlock(required=False)), ('quote', wagtail.blocks.BlockQuoteBlock(required=False)), ('video', wagtail.embeds.blocks.EmbedBlock(required=False)), ('code_snippet', wagtail.blocks.TextBlock(form_classname='Code Snippet', required=False))], use_json_field=True),
        ),
    ]
